# Generated by Django 5.0.6 on 2024-06-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0004_alter_estudiante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
