# Generated by Django 5.0.6 on 2024-06-11 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0005_estudiante_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permuta',
            name='asignatura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='Permutas.asignatura'),
            preserve_default=False,
        ),
    ]
