# Generated by Django 5.0.6 on 2024-06-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0007_alter_estudiante_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ManyToManyField(to='Permutas.grado'),
        ),
    ]
