# Generated by Django 5.0.6 on 2024-06-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0008_grado_asignatura_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ManyToManyField(to='Permutas.grado'),
        ),
    ]
