# Generated by Django 5.0.6 on 2024-06-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0009_estudiante_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='grado',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Permutas.grado'),
            preserve_default=False,
        ),
    ]
