# Generated by Django 5.0.6 on 2024-06-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0010_remove_estudiante_grado_remove_asignatura_grado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Permutas.grado'),
            preserve_default=False,
        ),
    ]
