# Generated by Django 5.0.6 on 2024-06-11 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0011_estudiante_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='domicilio',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='provincia',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.CharField(default=34667525025, max_length=15, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe ingresarse en el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
