# Generated by Django 5.0.6 on 2024-06-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0013_permuta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='poblacion',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permuta',
            name='estudiante2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permuta_estudiante2', to='Permutas.estudiante'),
        ),
        migrations.AlterField(
            model_name='permuta',
            name='grupo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permuta_grupo2', to='Permutas.grupo'),
        ),
    ]
