# Generated by Django 5.0.6 on 2024-06-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0014_estudiante_poblacion_alter_permuta_estudiante2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='nombre_asignatura',
            new_name='nombre',
        ),
    ]
