# Generated by Django 5.0.6 on 2024-06-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0015_rename_nombre_asignatura_asignatura_nombre'),
        ('Permutas', '0016_permuta_aceptada_1_permuta_aceptada_2_and_more'),
    ]

    operations = [
    ]
