# Generated by Django 5.0.6 on 2024-06-23 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0017_merge_20240623_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='estudiante',
            field=models.ManyToManyField(blank=True, to='Permutas.estudiante'),
        ),
        migrations.CreateModel(
            name='Solicitud_Permuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura_solicitada', to='Permutas.asignatura')),
                ('estudiante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_solicitud', to='Permutas.estudiante')),
                ('grupo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_solicitud', to='Permutas.grupo')),
                ('grupo_deseado', models.ManyToManyField(to='Permutas.grupo')),
            ],
        ),
    ]
