# Generated by Django 5.0.6 on 2024-06-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0018_alter_grupo_estudiante_solicitud_permuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='codigo_postal',
            field=models.CharField(default=11300, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permuta',
            name='estudiante2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permuta_estudiante2', to='Permutas.estudiante'),
        ),
        migrations.AlterField(
            model_name='permuta',
            name='grupo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permuta_grupo2', to='Permutas.grupo'),
        ),
    ]
