# Generated by Django 5.0.6 on 2024-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0019_estudiante_codigo_postal_alter_permuta_estudiante2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
