# Generated by Django 5.0.6 on 2024-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0020_alter_asignatura_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='proyecto_docente',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
