# Generated by Django 5.0.6 on 2024-06-30 07:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0021_grupo_proyecto_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='curso',
            field=models.CharField(choices=[('primero', 'Primero'), ('segundo', 'Segundo'), ('tercero', 'Tercero'), ('cuarto', 'Cuarto')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
