# Generated by Django 5.0.6 on 2024-07-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Permutas', '0023_rename_estudiante1_solicitud_permuta_estudiante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud_permuta',
            name='grupo_deseado',
        ),
        migrations.AddField(
            model_name='solicitud_permuta',
            name='grupos_deseados',
            field=models.ManyToManyField(blank=True, related_name='deseos_permuta', to='Permutas.grupo'),
        ),
        migrations.AlterField(
            model_name='solicitud_permuta',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permuta', to='Permutas.asignatura'),
        ),
        migrations.AlterField(
            model_name='solicitud_permuta',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permuta', to='Permutas.estudiante'),
        ),
        migrations.AlterField(
            model_name='solicitud_permuta',
            name='grupo_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_permuta', to='Permutas.grupo'),
        ),
    ]
